### ISSUE TITLE
关于日历界面切换的问题

### ISSUE THREAD

**Issue by YoujieXia** [soyaine/diary#1]
- 在点击某具体日期弹出页面后，点击右上角“No. XXX”回到日历界面，但是再次点击右上角“X”，却返回不了使用底层“使用说明”页面。
- 经尝试，仅有重新点击导航栏的“Diary”后第一次点“X”可见“使用说明”页面，若刷新不能解决问题。

- 已clone你的repo，目前效果请见 [live](https://youjiexia.github.io/diary/).
-------
PS：很喜欢你个人网站的风格，如果不介意的话，请求互换友链接。

**Comment by soyaine** [comment]
1. 底层“使用说明”页面实际是 index 页面的内容，也就是在 xx.github.io/diary/ 页面下，无具体文章时会显示的页面。右上角 “X” 实际是「日历」和「文章」的切换按钮。
2. 我正在不断改进这个主题，欢迎分享你的想法~
3. 如果在日历界面点击右上角 “X” 后出现“使用说明”，那么再回到文章内容的页面逻辑可能需要调整一下。
4. 很高兴你喜欢我的网站~ \(^o^)/~  可以互换友链。我的网址： [Soyaine] (https://soyaine.github.io)

**Comment by YoujieXia** [comment]
1. 嗯哈，我明白了哈，是我误解了原始的设计意图。后续有需要我可能自己调整哈~
2. 已经添加你的网址链接([live](https://youjiexia.github.io/collection/#友情链接))，我的网址：[Youjie Xia] ([https://youjiexia.github.io](https://youjiexia.github.io)).
3. 后续有问题会再和你交流的哈~这个issue可以close了。

**Comment by soyaine** [comment]
好哒，稍后我会添加你的链接。
